mesh_file = "lbracket.msh"
converted_mesh_file = "lbracket_mesh.dat"
mesh_order = 1
force_magnitude = 0.1
filter_radius = 0.02
optimization_type = "MWS"

[Material]
epsilon_constitutive = 1e-3
epsilon_stress = 1e-6
simp_exponent = 3
stress_exponent = 0.5
youngs_modulus = 100.0
youngs_modulus_stress = 100.0
poissons_ratio = 0.3

[Aggregation]
num_aggregation_regions = 20
aggregation_multiplier = 20

[Optimization]
# If NLOpt is used, max_iters is actually max function evaluations.
max_iters = 10000
absolute_tol = 1e-8
acceptable_tol = 1e-8
acceptable_iters = 10
accept_every_trial_step = false
compliance_limit = 3e-4
stress_limit = 0.5
mass_limit = 0.35
mean_change_iters = 10
mean_change_tol = 0
verbosity_level = 6
reassign_regions_interval = 1000
stress_alpha = 0
