mesh_file = "lbracket.msh"
mesh_order = 1
force_magnitude = 0.1
filter_radius = 0.02

[Material]
epsilon_constitutive = 1e-3
epsilon_stress = 1e-6
simp_exponent = 3
stress_exponent = 0.5
youngs_modulus = 100.0
youngs_modulus_stress = 100.0
poissons_ratio = 0.3

[Aggregation]
num_aggregation_regions = 5
aggregation_multiplier = 6

[Optimization]
# If NLOpt is used, max_iters is actually max function evaluations.
max_iters = 1
absolute_tol = 1e-8
acceptable_tol = 1e-6
acceptable_iters = 10
accept_every_trial_step = false
compliance_limit = 40
stress_limit = 0.3
mass_limit = 350
mean_change_iters = 10
mean_change_tol = 0
verbosity_level = 4
reassign_regions_interval = 10000
stress_alpha = 0.5